# Generated by Django 3.1.4 on 2022-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo_code',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='promo_codes',
            field=models.ManyToManyField(to='product.Promo_code'),
        ),
    ]
