# Generated by Django 3.1.4 on 2022-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DP',
            field=models.ImageField(blank=True, null=True, upload_to='DP/'),
        ),
    ]
